version: "3.8"

services:
  orthanc:
    image: osimis/orthanc-plugins:latest
    container_name: orthanc
    restart: always
    ports:
      - "8042:8042" # Web UI
      - "4242:4242" # DICOM Port
    environment:
      # Login Web UI
      ORTHANC__REGISTERED_USERS: |
        {
          "admin": "admin123"
        }

      # Konfigurasi dasar
      ORTHANC__NAME: "OrthancDocker"
      ORTHANC__DICOM_AET: "ORTHANC"
      ORTHANC__DICOM_PORT: 4242
      ORTHANC__REMOTE_ACCESS_ALLOWED: "true"

      # Remote DICOM Router
      ORTHANC__DICOM_MODALITIES: |
        {
          "DCMROUTER": ["172.18.1.2", 11112, "DCMROUTER"]
        }

      # Aktifkan DICOMweb plugin
      ORTHANC__DICOM_WEB__ENABLE: "true"
      ORTHANC__DICOM_WEB__ROOT: "/dicom-web/"

      # Folder penyimpanan DICOM
      ORTHANC__STORAGE_DIRECTORY: "/var/lib/orthanc/db"

    volumes:
      - ./orthanc-db:/var/lib/orthanc/db
