version: "3.8"

services:
  orthanc:
    image: orthancteam/orthanc:latest
    container_name: orthanc
    restart: always
    ports:
      - "8042:8042" # Web UI
      - "4242:4242" # DICOM port
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - orthanc-data:/var/lib/orthanc/db
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
    networks:
      - docker-dicom-satusehat_dicom-network # gunakan network router yang sudah ada

networks:
  docker-dicom-satusehat_dicom-network:
    external: true # hubungkan ke network yang sudah ada (punya dicom-router)

volumes:
  orthanc-data:
